/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkResponseApi } from './NetworkResponseApi';
import {
    NetworkResponseApiFromJSON,
    NetworkResponseApiFromJSONTyped,
    NetworkResponseApiToJSON,
} from './NetworkResponseApi';

/**
 * 
 * @export
 * @interface AddressResponseApi
 */
export interface AddressResponseApi {
    /**
     * 
     * @type {number}
     * @memberof AddressResponseApi
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseApi
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof AddressResponseApi
     */
    accountId?: number;
    /**
     * 
     * @type {Array<NetworkResponseApi>}
     * @memberof AddressResponseApi
     */
    networks?: Array<NetworkResponseApi>;
}

/**
 * Check if a given object implements the AddressResponseApi interface.
 */
export function instanceOfAddressResponseApi(value: object): boolean {
    return true;
}

export function AddressResponseApiFromJSON(json: any): AddressResponseApi {
    return AddressResponseApiFromJSONTyped(json, false);
}

export function AddressResponseApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressResponseApi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'address': json['address'] == null ? undefined : json['address'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'networks': json['networks'] == null ? undefined : ((json['networks'] as Array<any>).map(NetworkResponseApiFromJSON)),
    };
}

export function AddressResponseApiToJSON(value?: AddressResponseApi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'address': value['address'],
        'accountId': value['accountId'],
        'networks': value['networks'] == null ? undefined : ((value['networks'] as Array<any>).map(NetworkResponseApiToJSON)),
    };
}

