/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommonOrderType = {
    Limit: 'Limit',
    Market: 'Market',
    Other: 'Other'
} as const;
export type CommonOrderType = typeof CommonOrderType[keyof typeof CommonOrderType];


export function instanceOfCommonOrderType(value: any): boolean {
    return Object.values(CommonOrderType).includes(value);
}

export function CommonOrderTypeFromJSON(json: any): CommonOrderType {
    return CommonOrderTypeFromJSONTyped(json, false);
}

export function CommonOrderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonOrderType {
    return json as CommonOrderType;
}

export function CommonOrderTypeToJSON(value?: CommonOrderType | null): any {
    return value as any;
}

