/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAddressRequestApi
 */
export interface CreateAddressRequestApi {
    /**
     * 
     * @type {string}
     * @memberof CreateAddressRequestApi
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAddressRequestApi
     */
    accountId?: number;
}

/**
 * Check if a given object implements the CreateAddressRequestApi interface.
 */
export function instanceOfCreateAddressRequestApi(value: object): boolean {
    return true;
}

export function CreateAddressRequestApiFromJSON(json: any): CreateAddressRequestApi {
    return CreateAddressRequestApiFromJSONTyped(json, false);
}

export function CreateAddressRequestApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAddressRequestApi {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function CreateAddressRequestApiToJSON(value?: CreateAddressRequestApi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'accountId': value['accountId'],
    };
}

