/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiCredentialRequestApi
 */
export interface CreateApiCredentialRequestApi {
    /**
     * 
     * @type {string}
     * @memberof CreateApiCredentialRequestApi
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiCredentialRequestApi
     */
    apiSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiCredentialRequestApi
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateApiCredentialRequestApi
     */
    accountId?: number;
}

/**
 * Check if a given object implements the CreateApiCredentialRequestApi interface.
 */
export function instanceOfCreateApiCredentialRequestApi(value: object): boolean {
    return true;
}

export function CreateApiCredentialRequestApiFromJSON(json: any): CreateApiCredentialRequestApi {
    return CreateApiCredentialRequestApiFromJSONTyped(json, false);
}

export function CreateApiCredentialRequestApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiCredentialRequestApi {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'apiSecret': json['apiSecret'] == null ? undefined : json['apiSecret'],
        'password': json['password'] == null ? undefined : json['password'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function CreateApiCredentialRequestApiToJSON(value?: CreateApiCredentialRequestApi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiKey': value['apiKey'],
        'apiSecret': value['apiSecret'],
        'password': value['password'],
        'accountId': value['accountId'],
    };
}

