/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExchangerType = {
    Binance: 'Binance',
    Bybit: 'Bybit',
    Okx: 'Okx',
    Bingx: 'Bingx'
} as const;
export type ExchangerType = typeof ExchangerType[keyof typeof ExchangerType];


export function instanceOfExchangerType(value: any): boolean {
    return Object.values(ExchangerType).includes(value);
}

export function ExchangerTypeFromJSON(json: any): ExchangerType {
    return ExchangerTypeFromJSONTyped(json, false);
}

export function ExchangerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangerType {
    return json as ExchangerType;
}

export function ExchangerTypeToJSON(value?: ExchangerType | null): any {
    return value as any;
}

