/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExchagerType = {
    Binance: 'Binance',
    Bybit: 'Bybit',
    Okx: 'Okx',
    Bingx: 'Bingx'
} as const;
export type ExchagerType = typeof ExchagerType[keyof typeof ExchagerType];


export function instanceOfExchagerType(value: any): boolean {
    return Object.values(ExchagerType).includes(value);
}

export function ExchagerTypeFromJSON(json: any): ExchagerType {
    return ExchagerTypeFromJSONTyped(json, false);
}

export function ExchagerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchagerType {
    return json as ExchagerType;
}

export function ExchagerTypeToJSON(value?: ExchagerType | null): any {
    return value as any;
}

