/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LongShortTradeRequest
 */
export interface LongShortTradeRequest {
    /**
     * 
     * @type {string}
     * @memberof LongShortTradeRequest
     */
    asset?: string;
    /**
     * 
     * @type {number}
     * @memberof LongShortTradeRequest
     */
    tradeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof LongShortTradeRequest
     */
    minQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof LongShortTradeRequest
     */
    maxQuantity?: number;
}

/**
 * Check if a given object implements the LongShortTradeRequest interface.
 */
export function instanceOfLongShortTradeRequest(value: object): boolean {
    return true;
}

export function LongShortTradeRequestFromJSON(json: any): LongShortTradeRequest {
    return LongShortTradeRequestFromJSONTyped(json, false);
}

export function LongShortTradeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LongShortTradeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': json['asset'] == null ? undefined : json['asset'],
        'tradeCount': json['tradeCount'] == null ? undefined : json['tradeCount'],
        'minQuantity': json['minQuantity'] == null ? undefined : json['minQuantity'],
        'maxQuantity': json['maxQuantity'] == null ? undefined : json['maxQuantity'],
    };
}

export function LongShortTradeRequestToJSON(value?: LongShortTradeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'asset': value['asset'],
        'tradeCount': value['tradeCount'],
        'minQuantity': value['minQuantity'],
        'maxQuantity': value['maxQuantity'],
    };
}

