/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface NetworkResponseApi
 */
export interface NetworkResponseApi {
    /**
     * 
     * @type {number}
     * @memberof NetworkResponseApi
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkResponseApi
     */
    addressId?: number;
    /**
     * 
     * @type {NetworkType}
     * @memberof NetworkResponseApi
     */
    networkType?: NetworkType;
}

/**
 * Check if a given object implements the NetworkResponseApi interface.
 */
export function instanceOfNetworkResponseApi(value: object): boolean {
    return true;
}

export function NetworkResponseApiFromJSON(json: any): NetworkResponseApi {
    return NetworkResponseApiFromJSONTyped(json, false);
}

export function NetworkResponseApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkResponseApi {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'addressId': json['addressId'] == null ? undefined : json['addressId'],
        'networkType': json['networkType'] == null ? undefined : NetworkTypeFromJSON(json['networkType']),
    };
}

export function NetworkResponseApiToJSON(value?: NetworkResponseApi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'addressId': value['addressId'],
        'networkType': NetworkTypeToJSON(value['networkType']),
    };
}

