/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface UpsertNetworkRequestApi
 */
export interface UpsertNetworkRequestApi {
    /**
     * 
     * @type {number}
     * @memberof UpsertNetworkRequestApi
     */
    addressId?: number;
    /**
     * 
     * @type {NetworkType}
     * @memberof UpsertNetworkRequestApi
     */
    networkType?: NetworkType;
}

/**
 * Check if a given object implements the UpsertNetworkRequestApi interface.
 */
export function instanceOfUpsertNetworkRequestApi(value: object): boolean {
    return true;
}

export function UpsertNetworkRequestApiFromJSON(json: any): UpsertNetworkRequestApi {
    return UpsertNetworkRequestApiFromJSONTyped(json, false);
}

export function UpsertNetworkRequestApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertNetworkRequestApi {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['addressId'] == null ? undefined : json['addressId'],
        'networkType': json['networkType'] == null ? undefined : NetworkTypeFromJSON(json['networkType']),
    };
}

export function UpsertNetworkRequestApiToJSON(value?: UpsertNetworkRequestApi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'addressId': value['addressId'],
        'networkType': NetworkTypeToJSON(value['networkType']),
    };
}

