/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangerType } from './ExchangerType';
import {
    ExchangerTypeFromJSON,
    ExchangerTypeFromJSONTyped,
    ExchangerTypeToJSON,
} from './ExchangerType';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface WithdrawManualBatchRequest
 */
export interface WithdrawManualBatchRequest {
    /**
     * 
     * @type {ExchangerType}
     * @memberof WithdrawManualBatchRequest
     */
    exchanger?: ExchangerType;
    /**
     * 
     * @type {string}
     * @memberof WithdrawManualBatchRequest
     */
    asset?: string;
    /**
     * 
     * @type {NetworkType}
     * @memberof WithdrawManualBatchRequest
     */
    network?: NetworkType;
    /**
     * 
     * @type {number}
     * @memberof WithdrawManualBatchRequest
     */
    quantity?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof WithdrawManualBatchRequest
     */
    adresses?: Array<string>;
}

/**
 * Check if a given object implements the WithdrawManualBatchRequest interface.
 */
export function instanceOfWithdrawManualBatchRequest(value: object): boolean {
    return true;
}

export function WithdrawManualBatchRequestFromJSON(json: any): WithdrawManualBatchRequest {
    return WithdrawManualBatchRequestFromJSONTyped(json, false);
}

export function WithdrawManualBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawManualBatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exchanger': json['exchanger'] == null ? undefined : ExchangerTypeFromJSON(json['exchanger']),
        'asset': json['asset'] == null ? undefined : json['asset'],
        'network': json['network'] == null ? undefined : NetworkTypeFromJSON(json['network']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'adresses': json['adresses'] == null ? undefined : json['adresses'],
    };
}

export function WithdrawManualBatchRequestToJSON(value?: WithdrawManualBatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exchanger': ExchangerTypeToJSON(value['exchanger']),
        'asset': value['asset'],
        'network': NetworkTypeToJSON(value['network']),
        'quantity': value['quantity'],
        'adresses': value['adresses'],
    };
}

