/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangerType } from './ExchangerType';
import {
    ExchangerTypeFromJSON,
    ExchangerTypeFromJSONTyped,
    ExchangerTypeToJSON,
} from './ExchangerType';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface WithdrawManualRequest
 */
export interface WithdrawManualRequest {
    /**
     * 
     * @type {ExchangerType}
     * @memberof WithdrawManualRequest
     */
    exchanger?: ExchangerType;
    /**
     * 
     * @type {string}
     * @memberof WithdrawManualRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawManualRequest
     */
    asset?: string;
    /**
     * 
     * @type {NetworkType}
     * @memberof WithdrawManualRequest
     */
    network?: NetworkType;
    /**
     * 
     * @type {number}
     * @memberof WithdrawManualRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the WithdrawManualRequest interface.
 */
export function instanceOfWithdrawManualRequest(value: object): boolean {
    return true;
}

export function WithdrawManualRequestFromJSON(json: any): WithdrawManualRequest {
    return WithdrawManualRequestFromJSONTyped(json, false);
}

export function WithdrawManualRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawManualRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exchanger': json['exchanger'] == null ? undefined : ExchangerTypeFromJSON(json['exchanger']),
        'address': json['address'] == null ? undefined : json['address'],
        'asset': json['asset'] == null ? undefined : json['asset'],
        'network': json['network'] == null ? undefined : NetworkTypeFromJSON(json['network']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function WithdrawManualRequestToJSON(value?: WithdrawManualRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exchanger': ExchangerTypeToJSON(value['exchanger']),
        'address': value['address'],
        'asset': value['asset'],
        'network': NetworkTypeToJSON(value['network']),
        'quantity': value['quantity'],
    };
}

