/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchagerType } from './ExchagerType';
import {
    ExchagerTypeFromJSON,
    ExchagerTypeFromJSONTyped,
    ExchagerTypeToJSON,
} from './ExchagerType';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface WithdrawBatchRequest
 */
export interface WithdrawBatchRequest {
    /**
     * 
     * @type {ExchagerType}
     * @memberof WithdrawBatchRequest
     */
    exchanger?: ExchagerType;
    /**
     * 
     * @type {string}
     * @memberof WithdrawBatchRequest
     */
    asset?: string;
    /**
     * 
     * @type {NetworkType}
     * @memberof WithdrawBatchRequest
     */
    network?: NetworkType;
    /**
     * 
     * @type {number}
     * @memberof WithdrawBatchRequest
     */
    quantity?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof WithdrawBatchRequest
     */
    adresses?: Array<string>;
}

/**
 * Check if a given object implements the WithdrawBatchRequest interface.
 */
export function instanceOfWithdrawBatchRequest(value: object): boolean {
    return true;
}

export function WithdrawBatchRequestFromJSON(json: any): WithdrawBatchRequest {
    return WithdrawBatchRequestFromJSONTyped(json, false);
}

export function WithdrawBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawBatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exchanger': json['exchanger'] == null ? undefined : ExchagerTypeFromJSON(json['exchanger']),
        'asset': json['asset'] == null ? undefined : json['asset'],
        'network': json['network'] == null ? undefined : NetworkTypeFromJSON(json['network']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'adresses': json['adresses'] == null ? undefined : json['adresses'],
    };
}

export function WithdrawBatchRequestToJSON(value?: WithdrawBatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exchanger': ExchagerTypeToJSON(value['exchanger']),
        'asset': value['asset'],
        'network': NetworkTypeToJSON(value['network']),
        'quantity': value['quantity'],
        'adresses': value['adresses'],
    };
}

