/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchagerType } from './ExchagerType';
import {
    ExchagerTypeFromJSON,
    ExchagerTypeFromJSONTyped,
    ExchagerTypeToJSON,
} from './ExchagerType';
import type { NetworkType } from './NetworkType';
import {
    NetworkTypeFromJSON,
    NetworkTypeFromJSONTyped,
    NetworkTypeToJSON,
} from './NetworkType';

/**
 * 
 * @export
 * @interface WithdrawRequest
 */
export interface WithdrawRequest {
    /**
     * 
     * @type {ExchagerType}
     * @memberof WithdrawRequest
     */
    exchanger?: ExchagerType;
    /**
     * 
     * @type {string}
     * @memberof WithdrawRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawRequest
     */
    asset?: string;
    /**
     * 
     * @type {NetworkType}
     * @memberof WithdrawRequest
     */
    network?: NetworkType;
    /**
     * 
     * @type {number}
     * @memberof WithdrawRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the WithdrawRequest interface.
 */
export function instanceOfWithdrawRequest(value: object): boolean {
    return true;
}

export function WithdrawRequestFromJSON(json: any): WithdrawRequest {
    return WithdrawRequestFromJSONTyped(json, false);
}

export function WithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exchanger': json['exchanger'] == null ? undefined : ExchagerTypeFromJSON(json['exchanger']),
        'address': json['address'] == null ? undefined : json['address'],
        'asset': json['asset'] == null ? undefined : json['asset'],
        'network': json['network'] == null ? undefined : NetworkTypeFromJSON(json['network']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function WithdrawRequestToJSON(value?: WithdrawRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exchanger': ExchagerTypeToJSON(value['exchanger']),
        'address': value['address'],
        'asset': value['asset'],
        'network': NetworkTypeToJSON(value['network']),
        'quantity': value['quantity'],
    };
}

