/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SyncAddressRequest,
} from '../models/index';
import {
    SyncAddressRequestFromJSON,
    SyncAddressRequestToJSON,
} from '../models/index';

export interface SyncRequest {
    syncAddressRequest: SyncAddressRequest;
}

/**
 * 
 */
export class SyncAddressesEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async syncRaw(requestParameters: SyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['syncAddressRequest'] == null) {
            throw new runtime.RequiredError(
                'syncAddressRequest',
                'Required parameter "syncAddressRequest" was null or undefined when calling sync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sync-addresses`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SyncAddressRequestToJSON(requestParameters['syncAddressRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async sync(requestParameters: SyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.syncRaw(requestParameters, initOverrides);
    }

}
