/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  VolumeTradeRequest,
} from '../models/index';
import {
    VolumeTradeRequestFromJSON,
    VolumeTradeRequestToJSON,
} from '../models/index';

export interface VolumeTradeOperationRequest {
    volumeTradeRequest: VolumeTradeRequest;
}

/**
 * 
 */
export class TradeEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async volumeTradeRaw(requestParameters: VolumeTradeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['volumeTradeRequest'] == null) {
            throw new runtime.RequiredError(
                'volumeTradeRequest',
                'Required parameter "volumeTradeRequest" was null or undefined when calling volumeTrade().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/volume-trade`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VolumeTradeRequestToJSON(requestParameters['volumeTradeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async volumeTrade(requestParameters: VolumeTradeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.volumeTradeRaw(requestParameters, initOverrides);
    }

}
