/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WithdrawBatchRequest,
  WithdrawRequest,
} from '../models/index';
import {
    WithdrawBatchRequestFromJSON,
    WithdrawBatchRequestToJSON,
    WithdrawRequestFromJSON,
    WithdrawRequestToJSON,
} from '../models/index';

export interface WithdrawOperationRequest {
    withdrawRequest: WithdrawRequest;
}

export interface WithdrawBatchOperationRequest {
    withdrawBatchRequest: WithdrawBatchRequest;
}

/**
 * 
 */
export class WithdrawEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async withdrawRaw(requestParameters: WithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['withdrawRequest'] == null) {
            throw new runtime.RequiredError(
                'withdrawRequest',
                'Required parameter "withdrawRequest" was null or undefined when calling withdraw().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawRequestToJSON(requestParameters['withdrawRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async withdraw(requestParameters: WithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdrawRaw(requestParameters, initOverrides);
    }

    /**
     */
    async withdrawBatchRaw(requestParameters: WithdrawBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['withdrawBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'withdrawBatchRequest',
                'Required parameter "withdrawBatchRequest" was null or undefined when calling withdrawBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/withdraw-batch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawBatchRequestToJSON(requestParameters['withdrawBatchRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async withdrawBatch(requestParameters: WithdrawBatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdrawBatchRaw(requestParameters, initOverrides);
    }

}
