/* tslint:disable */
/* eslint-disable */
/**
 * Exchanger Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WithdrawManualBatchRequest,
  WithdrawManualRequest,
  WithdrawRequest,
} from '../models/index';
import {
    WithdrawManualBatchRequestFromJSON,
    WithdrawManualBatchRequestToJSON,
    WithdrawManualRequestFromJSON,
    WithdrawManualRequestToJSON,
    WithdrawRequestFromJSON,
    WithdrawRequestToJSON,
} from '../models/index';

export interface WithdrawOperationRequest {
    withdrawRequest: WithdrawRequest;
}

export interface Withdraw1Request {
    withdrawManualRequest: WithdrawManualRequest;
}

export interface WithdrawBatchRequest {
    withdrawManualBatchRequest: WithdrawManualBatchRequest;
}

/**
 * 
 */
export class WithdrawEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async withdrawRaw(requestParameters: WithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['withdrawRequest'] == null) {
            throw new runtime.RequiredError(
                'withdrawRequest',
                'Required parameter "withdrawRequest" was null or undefined when calling withdraw().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawRequestToJSON(requestParameters['withdrawRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async withdraw(requestParameters: WithdrawOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdrawRaw(requestParameters, initOverrides);
    }

    /**
     */
    async withdraw1Raw(requestParameters: Withdraw1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['withdrawManualRequest'] == null) {
            throw new runtime.RequiredError(
                'withdrawManualRequest',
                'Required parameter "withdrawManualRequest" was null or undefined when calling withdraw1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/withdraw1`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawManualRequestToJSON(requestParameters['withdrawManualRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async withdraw1(requestParameters: Withdraw1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdraw1Raw(requestParameters, initOverrides);
    }

    /**
     */
    async withdrawBatchRaw(requestParameters: WithdrawBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['withdrawManualBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'withdrawManualBatchRequest',
                'Required parameter "withdrawManualBatchRequest" was null or undefined when calling withdrawBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/withdraw1-batch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawManualBatchRequestToJSON(requestParameters['withdrawManualBatchRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async withdrawBatch(requestParameters: WithdrawBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.withdrawBatchRaw(requestParameters, initOverrides);
    }

}
