/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CommonOrderType = "Limit" | "Market" | "Other";

export type ExchagerType = "Binance" | "Bybit" | "Okx" | "Bingx";

export type LongShortTradeRequest = {
  asset?: string | null;
  /**
   * @format int32
   */
  tradeCount?: number;
  /**
   * @format double
   */
  minQuantity?: number;
  /**
   * @format double
   */
  maxQuantity?: number;
};

export type NetworkType =
  | "Tron"
  | "BSC"
  | "Avax"
  | "Arbitrum"
  | "Optimism"
  | "Solana";

export type ProxyResponseApi = {
  /**
   * @format int32
   */
  id?: number;
  name?: string | null;
  host?: string | null;
  /**
   * @format int32
   */
  port?: number;
  login?: string | null;
  pass?: string | null;
  /**
   * @format date-time
   */
  endDate?: string | null;
  provider?: string | null;
  note?: string | null;
  active?: boolean;
};

export type UpsertProxyRequestApi = {
  name?: string | null;
  host?: string | null;
  /**
   * @format int32
   */
  port?: number;
  login?: string | null;
  pass?: string | null;
  note?: string | null;
  /**
   * @format date-time
   */
  endDate?: string | null;
  active?: boolean;
  provider?: string | null;
};

export type VolumeTradeRequest = {
  exchanger?: ExchagerType;
  asset?: string | null;
  /**
   * @format double
   */
  volume?: number;
  orderType?: CommonOrderType;
  autoTransfer?: boolean;
};

export type WithdrawBatchRequest = {
  exchanger?: ExchagerType;
  asset?: string | null;
  network?: NetworkType;
  /**
   * @format double
   */
  quantity?: number;
  adresses?: string[] | null;
};

export type WithdrawRequest = {
  exchanger?: ExchagerType;
  address?: string | null;
  asset?: string | null;
  network?: NetworkType;
  /**
   * @format double
   */
  quantity?: number;
};
